/***************************************************************************************************
 * city_accelerator_nowater.v -- 10 MHz overlapped sliding-column implementation for MAX 10
 *
 * Purpose
 *   A resource-bounded hardware implementation of the active nescity.c rule.
 *   The CPU/MMIO side remains in the NES/cart clock domain (clk_cpu, nominally 100 MHz),
 *   while the simulation engine runs from a PLL-generated 10 MHz clock (clk_calc).
 *
 * Implementation
 *   - Reuse four of five neighborhood columns as x advances.
 *   - Overlap five next-column reads with arithmetic, then write one result.
 *   - Keep one synchronous RAM read latency; compute a cell every six clocks.
 *   - Decompose weight = (3 - abs(dy)) + (2 - abs(dx)).
 *   - Keep the 2 KiB dual-clock grid RAM and the existing START/DONE handshake.
 *   - Explicitly bound arithmetic, including byte values above 100 written by CPU.
 *   See eval/README.md for verification and resource estimates.
 *
 * Current simulation rule (same as active nescity.c)
 *   - 32 x 30 grid, 8-bit cells
 *   - 5 x 5 Manhattan-weighted neighborhood, torus boundary
 *   - simultaneous update using private double buffers
 *   - compute_water_penalty() is disabled, so water_penalty == 0
 *
 * CPU map after CITY unlock
 *   $6000-$63BF : active grid[960]
 *   $7F00       : 'C'
 *   $7F01       : 'A'
 *   $7F02       : interface version = 05h
 *   $7F03       : display/batch interval (01..FF=1..255, 00=256)
 *   $7F10       : control, bit0 START, bit1 soft reset (only accepted while idle)
 *   $7F11       : status, bit0 BUSY, bit1 DONE
 *   $7F12/$7F13 : completed step count, low/high
 *   $7F14       : water penalty (always 0)
 *
 * Unlock sequence while disabled
 *   $7FF0='C', $7FF1='I', $7FF2='T', $7FF3='Y'
 *
 * CPU grid behavior while BUSY
 *   read  -> FFh
 *   write -> ignored
 ***************************************************************************************************/

module city_accelerator_nowater
(
  input  wire        clk_cpu,// 100 MHz
  input  wire        clk_calc,// 10 MHz
  input  wire        reset,

  input  wire        cpu_sel,
  input  wire        cpu_we,
  input  wire        cpu_re,
  input  wire [12:0] cpu_addr,
  input  wire [ 7:0] cpu_din,
  output reg  [ 7:0] cpu_dout,
  output wire        cpu_dout_oe,
  output wire        cpu_claim,
  output wire        busy_out
);

// Number of accelerator steps executed between screen redraws by the NES program.
// 1..255 are returned directly from $7F03; 256 is encoded as 00h.
localparam integer DISPLAY_STEP_INTERVAL = 256;
localparam [7:0] DISPLAY_STEP_INTERVAL_CODE =
    (DISPLAY_STEP_INTERVAL == 256) ? 8'h00 : DISPLAY_STEP_INTERVAL[7:0];

localparam [10:0] GRID_BANK0_BASE = 11'd0;
localparam [10:0] GRID_BANK1_BASE = 11'd960;

// -------------------------------------------------------------------------------------------------
// CPU / MMIO clock domain (clk_cpu)
// -------------------------------------------------------------------------------------------------
reg        accel_enabled;
reg [1:0]  unlock_state;
reg        cpu_unlock_write_d;

reg        active_bank_cpu;
reg        busy_cpu;
reg        done_flag_cpu;
reg [15:0] step_count_cpu;

// START request crossing CPU -> calculator.
reg start_toggle_cpu;
reg start_bank_cpu;
// The learned path is valid only after an exact initial-grid match and until a
// CPU edit/reset. These request fields remain stable until DONE (bundled CDC).
reg training_valid_cpu;
reg start_validate_cpu, start_model_cpu, start_trajectory_cpu;
reg trajectory_valid_calc;
// BEGIN LEARNED LIMITS (generated by eval/learned.py)
localparam [15:0] LEARNED_FIRST = 16'd86;
localparam [15:0] LEARNED_END = 16'd1280;
// END LEARNED LIMITS

// DONE event crossing calculator -> CPU.
reg done_toggle_sync1;
reg done_toggle_sync2;
reg done_toggle_seen_cpu;
// Generated in clk_calc domain; declared here because the CPU synchronizer reads it.
reg done_toggle_calc;
wire done_event_cpu = done_toggle_sync2 ^ done_toggle_seen_cpu;

wire cpu_reg_sel  = cpu_sel && accel_enabled && (cpu_addr[12:8] == 5'h1F);
wire cpu_grid_sel = cpu_sel && accel_enabled && (cpu_addr < 13'h03C0);
wire [9:0] cpu_grid_index = cpu_addr[9:0];

wire cpu_unlock_write =
    cpu_sel && cpu_we && !accel_enabled && (cpu_addr[12:4] == 9'h1FF);
wire cpu_unlock_write_pulse = cpu_unlock_write && !cpu_unlock_write_d;

assign busy_out = accel_enabled && busy_cpu;
assign cpu_claim = cpu_reg_sel || cpu_grid_sel;
assign cpu_dout_oe = cpu_sel && cpu_re && cpu_claim;

// -------------------------------------------------------------------------------------------------
// Private grid RAM
//   Port A: clk_calc, calculator
//   Port B: clk_cpu, CPU grid window
// -------------------------------------------------------------------------------------------------
wire       calc_grid_we;
wire [10:0] calc_grid_addr;
wire [7:0]  calc_grid_din;
wire [7:0] calc_grid_dout;

wire       cpu_grid_ram_we;
wire [10:0] cpu_grid_ram_addr;
wire [7:0] cpu_grid_ram_dout;

function [10:0] bank_base;
  input bank;
  begin
    bank_base = bank ? GRID_BANK1_BASE : GRID_BANK0_BASE;
  end
endfunction

function [10:0] bank_addr;
  input bank;
  input [9:0] index;
  begin
    bank_addr = bank_base(bank) + {1'b0, index};
  end
endfunction

assign cpu_grid_ram_addr = bank_addr(active_bank_cpu, cpu_grid_index);
assign cpu_grid_ram_we   = cpu_grid_sel && cpu_we && !busy_cpu;

city_grid_dpram_dc #(.ADDR_WIDTH(11), .DATA_WIDTH(8)) city_grid_ram
(
  .clk_a  (clk_calc),
  .we_a   (calc_grid_we),
  .addr_a (calc_grid_addr),
  .data_a (calc_grid_din),
  .q_a    (calc_grid_dout),

  .clk_b  (clk_cpu),
  .we_b   (cpu_grid_ram_we),
  .addr_b (cpu_grid_ram_addr),
  .data_b (cpu_din),
  .q_b    (cpu_grid_ram_dout)
);

// -------------------------------------------------------------------------------------------------
// CPU read mux
// -------------------------------------------------------------------------------------------------
always @(*) begin
  cpu_dout = 8'h00;

  if (cpu_sel && cpu_re && accel_enabled) begin
    if (cpu_reg_sel) begin
      case (cpu_addr[7:0])
        8'h00: cpu_dout = 8'h43; // 'C'
        8'h01: cpu_dout = 8'h41; // 'A'
        8'h02: cpu_dout = 8'h05; // interface version kept compatible with current NES software
        8'h03: cpu_dout = DISPLAY_STEP_INTERVAL_CODE;
        8'h10: cpu_dout = 8'h00;
        8'h11: cpu_dout = {6'b000000, done_flag_cpu, busy_cpu};
        8'h12: cpu_dout = step_count_cpu[7:0];
        8'h13: cpu_dout = step_count_cpu[15:8];
        8'h14: cpu_dout = 8'h00; // water_penalty
        default: cpu_dout = 8'h00;
      endcase
    end else if (cpu_grid_sel) begin
      cpu_dout = busy_cpu ? 8'hFF : cpu_grid_ram_dout;
    end
  end
end

// CPU-domain control, unlock, and completion bookkeeping.
always @(posedge clk_cpu or posedge reset) begin
  if (reset) begin
    accel_enabled        <= 1'b0;
    unlock_state         <= 2'd0;
    cpu_unlock_write_d   <= 1'b0;
    active_bank_cpu      <= 1'b0;
    busy_cpu             <= 1'b0;
    done_flag_cpu        <= 1'b0;
    step_count_cpu       <= 16'd0;
    start_toggle_cpu     <= 1'b0;
    start_bank_cpu       <= 1'b0;
    training_valid_cpu   <= 1'b0;
    start_validate_cpu   <= 1'b0;
    start_model_cpu      <= 1'b0;
    start_trajectory_cpu <= 1'b0;
    done_toggle_sync1    <= 1'b0;
    done_toggle_sync2    <= 1'b0;
    done_toggle_seen_cpu <= 1'b0;
  end else begin
    cpu_unlock_write_d <= cpu_unlock_write;

    // Synchronize DONE toggle from the 10 MHz domain.
    done_toggle_sync1 <= done_toggle_calc;
    done_toggle_sync2 <= done_toggle_sync1;

    if (done_event_cpu) begin
      done_toggle_seen_cpu <= done_toggle_sync2;
      active_bank_cpu <= ~active_bank_cpu;
      step_count_cpu <= step_count_cpu + 16'd1;
      busy_cpu <= 1'b0;
      done_flag_cpu <= 1'b1;
      training_valid_cpu <= trajectory_valid_calc;
    end

    if (cpu_grid_ram_we) training_valid_cpu <= 1'b0;

    // CITY unlock is entirely in the CPU clock domain.
    if (cpu_unlock_write_pulse) begin
      case (unlock_state)
        2'd0: begin
          if (cpu_addr[3:0] == 4'h0 && cpu_din == 8'h43) unlock_state <= 2'd1;
          else                                            unlock_state <= 2'd0;
        end
        2'd1: begin
          if (cpu_addr[3:0] == 4'h1 && cpu_din == 8'h49) unlock_state <= 2'd2;
          else                                            unlock_state <= 2'd0;
        end
        2'd2: begin
          if (cpu_addr[3:0] == 4'h2 && cpu_din == 8'h54) unlock_state <= 2'd3;
          else                                            unlock_state <= 2'd0;
        end
        2'd3: begin
          if (cpu_addr[3:0] == 4'h3 && cpu_din == 8'h59) begin
            accel_enabled <= 1'b1;
            unlock_state <= 2'd0;
          end else begin
            unlock_state <= 2'd0;
          end
        end
        default: unlock_state <= 2'd0;
      endcase
    end

    // Control register.  START is converted to a toggle request so no pulse-width
    // assumption exists between the 100 MHz and 10 MHz domains.
    if (accel_enabled && cpu_sel && cpu_we && cpu_reg_sel && cpu_addr[7:0] == 8'h10) begin
      if (!busy_cpu && cpu_din[1]) begin
        active_bank_cpu <= 1'b0;
        step_count_cpu  <= 16'd0;
        training_valid_cpu <= 1'b0;
        done_flag_cpu   <= 1'b0;
      end

      if (!busy_cpu && cpu_din[0]) begin
        start_bank_cpu   <= active_bank_cpu;
        start_validate_cpu <= (step_count_cpu == 16'd0) && !cpu_din[1];
        start_trajectory_cpu <= training_valid_cpu && !cpu_din[1];
        start_model_cpu <= training_valid_cpu && !cpu_din[1] &&
            step_count_cpu >= LEARNED_FIRST && step_count_cpu < LEARNED_END;
        start_toggle_cpu <= ~start_toggle_cpu;
        busy_cpu         <= 1'b1;
        done_flag_cpu    <= 1'b0;
      end
    end
  end
end

// -------------------------------------------------------------------------------------------------
// Sliding-column 10 MHz calculator
// -------------------------------------------------------------------------------------------------
localparam [3:0] ST_IDLE      = 4'd0;
localparam [3:0] ST_INIT      = 4'd1;
localparam [3:0] ST_FILL      = 4'd2;
localparam [3:0] ST_DRAIN     = 4'd3;
localparam [3:0] ST_SUM       = 4'd4;
localparam [3:0] ST_AVG       = 4'd5;
localparam [3:0] ST_BIAS      = 4'd6;
localparam [3:0] ST_DELTA     = 4'd7;
localparam [3:0] ST_NEW_VALUE = 4'd8;
localparam [3:0] ST_WRITE     = 4'd9;
localparam [3:0] ST_FINISH    = 4'd10;
localparam [3:0] ST_MODEL_WAIT = 4'd11;
localparam [3:0] ST_MODEL      = 4'd12;
localparam [3:0] ST_GUARD      = 4'd13;
localparam [3:0] ST_GUARD_LAST = 4'd14;
reg [3:0] calc_state;

reg start_toggle_sync1, start_toggle_sync2, start_toggle_seen_calc;
reg start_bank_sync1, start_bank_sync2, source_bank_calc;
wire start_event_calc = start_toggle_sync2 ^ start_toggle_seen_calc;
reg [9:0] cell_index;
reg validate_sync1, validate_sync2, model_sync1, model_sync2;
reg trajectory_sync1, trajectory_sync2;
reg model_active_calc, predicted_cell, cache_ready;
reg [9:0] guard_index;
reg guard_match;
wire guarding = calc_state == ST_GUARD || calc_state == ST_GUARD_LAST;
// Synchronous 1024 x 9 ROM: 7-bit initial value + 2-bit prediction class.
// 00 abstains, 01 predicts 0, 10 predicts 1, 11 predicts 100.
wire [8:0] model_word;
wire [9:0] model_addr = guarding ? guard_index :
    ((calc_state == ST_WRITE && cell_index != 10'd959) ? cell_index + 10'd1 : cell_index);
city_learned_rom learned_rom (.clk(clk_calc), .address(model_addr), .q(model_word));
reg [4:0] issue_x, issue_y, row_top;
reg [2:0] issue_row, data_row1;
reg [4:0] reads_left;
reg read_valid;

// One calculator RAM port: five prefetch reads overlap SUM..NEW_VALUE, followed
// by one output write. At x=31 prefetch the first column of the following row.
wire read_issue = (calc_state == ST_FILL) ||
    ((cell_index != 10'd959) &&
     (calc_state == ST_SUM || calc_state == ST_AVG || calc_state == ST_BIAS ||
      calc_state == ST_DELTA || calc_state == ST_NEW_VALUE));

// Only five column summaries are cached, in ordinary registers (no extra M9K).
// v_sum <= 5*255, v_weight <= 9*255. The signed force coefficient is -2..3.
reg [10:0] col_sum [0:4];
reg [11:0] col_weight [0:4];
reg signed [4:0] col_force [0:4];
reg signed [6:0] col_force_weight [0:4];
reg [7:0] col_self [0:4];
reg [2:0] col_sea [0:4];
reg [2:0] col_mountain [0:4];
reg [2:0] col_natural [0:4];
reg [2:0] col_house [0:4];
reg [2:0] col_shop [0:4];
reg [2:0] col_tall [0:4];
reg [10:0] part_sum;
reg [11:0] part_weight;
reg signed [4:0] part_force;
reg signed [6:0] part_force_weight;
reg [7:0] part_self;
reg [2:0] part_sea;
reg [2:0] part_mountain;
reg [2:0] part_natural;
reg [2:0] part_house;
reg [2:0] part_shop;
reg [2:0] part_tall;
reg [14:0] weighted_sum_acc; // <= 65*255 = 16575
reg signed [8:0] raw_force_acc; // -130..195
reg [4:0] sea_count, mountain_count, natural_count;
reg [4:0] urban_count, house_count, shop_count, tall_count;
reg [7:0] self_value, avg_value, next_value;
reg signed [9:0] bias_value; // includes overcrowding for all byte inputs
reg signed [2:0] delta_value; // clamped to -3..1
integer c;

// Drive RAM inputs from registered state/counters, avoiding the old extra address
// register. RAM q itself is still registered: read_valid/data_row1 delay one cycle.
assign calc_grid_we = !reset && (calc_state == ST_WRITE);
assign calc_grid_addr = (calc_state == ST_WRITE) ?
    bank_addr(~source_bank_calc, cell_index) :
    bank_addr(source_bank_calc, guarding ? guard_index : {issue_y, issue_x});
assign calc_grid_din = next_value;


function [4:0] top_row;
  input [4:0] y;
  begin
    top_row = (y < 5'd2) ? y + 5'd28 : y - 5'd2;
  end
endfunction

// The 15..24 class contributes +2 independently of the weight. Its coefficient
// is zero; the +2 is included once in col_force_weight, never in col_force.
function signed [2:0] force_coefficient;
  input [7:0] v;
  begin
    if (v == 8'd0)      force_coefficient = 3'sd3;
    else if (v <= 8'd14) force_coefficient = -3'sd2;
    else if (v <= 8'd24) force_coefficient = 3'sd0;
    else if (v <= 8'd34) force_coefficient = 3'sd1;
    else if (v <= 8'd49) force_coefficient = 3'sd2;
    else if (v <= 8'd62) force_coefficient = 3'sd3;
    else if (v <= 8'd78) force_coefficient = 3'sd2;
    else                force_coefficient = 3'sd1;
  end
endfunction
wire signed [2:0] sample_force = force_coefficient(calc_grid_dout);
wire signed [6:0] sample_force_ext = {{4{sample_force[2]}}, sample_force};
wire sample_special = calc_grid_dout >= 8'd15 && calc_grid_dout <= 8'd24;
wire [11:0] sample_value = {4'd0, calc_grid_dout};
wire [11:0] sample_weight = (data_row1 == 3'd2) ?
    (sample_value << 1) + sample_value :
    ((data_row1 == 3'd1 || data_row1 == 3'd3) ? sample_value << 1 : sample_value);
wire signed [6:0] sample_force_weight =
    ((data_row1 == 3'd2) ? (sample_force_ext <<< 1) + sample_force_ext :
     ((data_row1 == 3'd1 || data_row1 == 3'd3) ? sample_force_ext <<< 1 : sample_force_ext))
    + (sample_special ? 7'sd2 : 7'sd0);
wire sample_sea = calc_grid_dout == 8'd0;
wire sample_mountain = calc_grid_dout == 8'd1;
wire sample_natural = calc_grid_dout >= 8'd1 && calc_grid_dout <= 8'd24;
wire sample_house = calc_grid_dout >= 8'd35 && calc_grid_dout <= 8'd62;
wire sample_shop = calc_grid_dout >= 8'd63 && calc_grid_dout <= 8'd78;
wire sample_tall = calc_grid_dout >= 8'd79 && calc_grid_dout <= 8'd100;

// Exact /65 without multiplier or general divider, for 0..16575 inclusive.
// q0 underestimates floor(n/65) by at most one; one remainder correction suffices.
function [7:0] divide65;
  input [14:0] n;
  reg [14:0] reduced, remainder;
  reg [7:0] q0;
  begin
    reduced = n - {6'd0, n[14:6]};
    q0 = reduced[13:6];
    remainder = n - {1'b0, q0, 6'd0} - {7'd0, q0};
    divide65 = q0 + ((remainder >= 15'd65) ? 8'd1 : 8'd0);
  end
endfunction

// Exact signed truncation of (raw_force - 20)/20 for raw_force in -130..195.
function signed [4:0] force_delta;
  input signed [8:0] rf;
  begin
    if      (rf >=  9'sd180) force_delta =  5'sd8;
    else if (rf >=  9'sd160) force_delta =  5'sd7;
    else if (rf >=  9'sd140) force_delta =  5'sd6;
    else if (rf >=  9'sd120) force_delta =  5'sd5;
    else if (rf >=  9'sd100) force_delta =  5'sd4;
    else if (rf >=  9'sd80)  force_delta =  5'sd3;
    else if (rf >=  9'sd60)  force_delta =  5'sd2;
    else if (rf >=  9'sd40)  force_delta =  5'sd1;
    else if (rf >   9'sd0)   force_delta =  5'sd0;
    else if (rf >  -9'sd20)  force_delta = -5'sd1;
    else if (rf >  -9'sd40)  force_delta = -5'sd2;
    else if (rf >  -9'sd60)  force_delta = -5'sd3;
    else if (rf >  -9'sd80)  force_delta = -5'sd4;
    else if (rf >  -9'sd100) force_delta = -5'sd5;
    else if (rf >  -9'sd120) force_delta = -5'sd6;
    else                    force_delta = -5'sd7;
  end
endfunction

function signed [9:0] calc_bias;
  input [7:0] self;
  input signed [8:0] rf;
  input [7:0] avg;
  input [4:0] sea, mountain, natural, urban, house, shop, tall;
  reg signed [9:0] b;
  reg [6:0] natural_pressure;
  reg [7:0] over_capacity, capacity_quotient;
  begin
    b = 10'sd0;
    natural_pressure = {2'd0, natural} + {1'b0, sea, 1'b0} + {1'b0, mountain, 1'b0};
    over_capacity = (avg > 8'd55) ? avg - 8'd55 : 8'd0;
    // Deliberately unsigned and byte-wide: no 32-bit signed divider.
    capacity_quotient = over_capacity / 8'd3;
    if (self <= 8'd1) b = b - 10'sd4;
    if (self >= 8'd1 && self <= 8'd34) begin
      if (house >= 5'd2) b = b + 10'sd2;
      if (house >= 5'd4) b = b + 10'sd2;
      if (house >= 5'd7) b = b + 10'sd2;
      if (shop >= 5'd1 && house >= 5'd3) b = b + 10'sd1;
      if (sea >= 5'd4) b = b - 10'sd2;
      if (mountain >= 5'd3 && house < 5'd4) b = b - 10'sd3;
      if (house < 5'd2) b = b - 10'sd3;
    end
    if (self >= 8'd35 && self <= 8'd62) begin
      if (shop >= 5'd1) b = b + 10'sd2;
      if (tall >= 5'd2) b = b + 10'sd1;
    end
    if (self >= 8'd63 && ({1'b0, shop} + {1'b0, tall}) >= 6'd4) b = b + 10'sd2;
    if (self >= 8'd35) begin
      if (urban < 5'd5) b = b - $signed({5'd0, (5'd5 - urban)});
      b = b - $signed({7'd0, natural_pressure[6:4]});
    end
    b = b - $signed({capacity_quotient, 2'b0});
    if (self >= 8'd25 && self < 8'd35 && urban < 5'd3 && rf < 9'sd12) b = b - 10'sd1;
    if (rf < 9'sd15 && self < 8'd35) b = b - 10'sd1;
    calc_bias = b;
  end
endfunction

function signed [2:0] calc_delta;
  input [7:0] self;
  input signed [8:0] rf;
  input [7:0] avg;
  input signed [9:0] bias;
  reg signed [9:0] d;
  reg signed [4:0] f;
  begin
    f = force_delta(rf);
    d = $signed({{5{f[4]}}, f}) + bias;
    if ({1'b0, avg} > {1'b0, self} + 9'd12) d = d + 10'sd1;
    if ({1'b0, avg} + 9'd20 < {1'b0, self}) d = d - 10'sd1;
    if (d > 10'sd1)       calc_delta = 3'sd1;
    else if (d < -10'sd3) calc_delta = -3'sd3;
    else                  calc_delta = d[2:0];
  end
endfunction

function [7:0] calc_new_value;
  input [7:0] self;
  input signed [2:0] delta;
  reg signed [9:0] nv;
  begin
    nv = $signed({2'b0, self}) + $signed({{7{delta[2]}}, delta});
    if (self == 8'd0)  calc_new_value = 8'd0;
    else if (nv < 10'sd1)   calc_new_value = 8'd1;
    else if (nv > 10'sd100) calc_new_value = 8'd100;
    else calc_new_value = nv[7:0];
    // self <= 1 can rise by at most 1, so the reference's >8 cap is unreachable.
  end
endfunction

always @(posedge clk_calc or posedge reset) begin
  if (reset) begin
    start_toggle_sync1 <= 1'b0;
    start_toggle_sync2 <= 1'b0;
    start_toggle_seen_calc <= 1'b0;
    start_bank_sync1 <= 1'b0;
    start_bank_sync2 <= 1'b0;
    source_bank_calc <= 1'b0;
    validate_sync1 <= 1'b0;
    validate_sync2 <= 1'b0;
    model_sync1 <= 1'b0;
    model_sync2 <= 1'b0;
    trajectory_sync1 <= 1'b0;
    trajectory_sync2 <= 1'b0;
    trajectory_valid_calc <= 1'b0;
    model_active_calc <= 1'b0;
    predicted_cell <= 1'b0;
    cache_ready <= 1'b0;
    guard_index <= 10'd0;
    guard_match <= 1'b0;
    done_toggle_calc <= 1'b0;
    calc_state <= ST_IDLE;
    cell_index <= 10'd0;
    issue_x <= 5'd0;
    issue_y <= 5'd0;
    row_top <= 5'd0;
    issue_row <= 3'd0;
    data_row1 <= 3'd0;
    reads_left <= 5'd0;
    read_valid <= 1'b0;
    part_sum <= 11'd0;
    part_weight <= 12'd0;
    part_force <= 5'sd0;
    part_force_weight <= 7'sd0;
    part_self <= 8'd0;
    part_sea <= 3'd0;
    part_mountain <= 3'd0;
    part_natural <= 3'd0;
    part_house <= 3'd0;
    part_shop <= 3'd0;
    part_tall <= 3'd0;
    weighted_sum_acc <= 15'd0;
    raw_force_acc <= 9'sd0;
    self_value <= 8'd0;
    avg_value <= 8'd0;
    bias_value <= 10'sd0;
    delta_value <= 3'sd0;
    next_value <= 8'd0;
    sea_count <= 5'd0;
    mountain_count <= 5'd0;
    natural_count <= 5'd0;
    urban_count <= 5'd0;
    house_count <= 5'd0;
    shop_count <= 5'd0;
    tall_count <= 5'd0;
    // col_* have no reset: all five entries are filled before each row is used.
  end else begin
    start_toggle_sync1 <= start_toggle_cpu;
    start_toggle_sync2 <= start_toggle_sync1;
    start_bank_sync1 <= start_bank_cpu;
    start_bank_sync2 <= start_bank_sync1;
    validate_sync1 <= start_validate_cpu;
    validate_sync2 <= validate_sync1;
    model_sync1 <= start_model_cpu;
    model_sync2 <= model_sync1;
    trajectory_sync1 <= start_trajectory_cpu;
    trajectory_sync2 <= trajectory_sync1;
    read_valid <= read_issue;
    data_row1 <= issue_row;
    if (read_issue) begin
      if (issue_row == 3'd4) begin
        issue_row <= 3'd0;
        issue_y <= row_top;
        issue_x <= issue_x + 5'd1;
      end else begin
        issue_row <= issue_row + 3'd1;
        issue_y <= (issue_y == 5'd29) ? 5'd0 : issue_y + 5'd1;
      end
    end

    // The reducer runs independently of arithmetic. Current-cell totals are
    // snapshotted in ST_SUM before the next column shifts the cache in ST_WRITE.
    if (read_valid) begin
      if (data_row1 == 3'd0) begin
        part_sum <= {3'd0, calc_grid_dout};
        part_weight <= sample_weight;
        part_force <= {{2{sample_force[2]}}, sample_force};
        part_force_weight <= sample_force_weight;
        part_sea <= {2'd0, sample_sea};
        part_mountain <= {2'd0, sample_mountain};
        part_natural <= {2'd0, sample_natural};
        part_house <= {2'd0, sample_house};
        part_shop <= {2'd0, sample_shop};
        part_tall <= {2'd0, sample_tall};
      end else begin
        part_sum <= part_sum + {3'd0, calc_grid_dout};
        part_weight <= part_weight + sample_weight;
        part_force <= part_force + $signed({{2{sample_force[2]}}, sample_force});
        part_force_weight <= part_force_weight + sample_force_weight;
        part_sea <= part_sea + {2'd0, sample_sea};
        part_mountain <= part_mountain + {2'd0, sample_mountain};
        part_natural <= part_natural + {2'd0, sample_natural};
        part_house <= part_house + {2'd0, sample_house};
        part_shop <= part_shop + {2'd0, sample_shop};
        part_tall <= part_tall + {2'd0, sample_tall};
      end
      if (data_row1 == 3'd2) part_self <= calc_grid_dout;
      if (data_row1 == 3'd4) begin
        for (c = 0; c < 4; c = c + 1) begin
          col_sum[c] <= col_sum[c+1];
          col_weight[c] <= col_weight[c+1];
          col_force[c] <= col_force[c+1];
          col_force_weight[c] <= col_force_weight[c+1];
          col_self[c] <= col_self[c+1];
          col_sea[c] <= col_sea[c+1];
          col_mountain[c] <= col_mountain[c+1];
          col_natural[c] <= col_natural[c+1];
          col_house[c] <= col_house[c+1];
          col_shop[c] <= col_shop[c+1];
          col_tall[c] <= col_tall[c+1];
        end
        col_sum[4] <= part_sum + {3'd0, calc_grid_dout};
        col_weight[4] <= part_weight + sample_weight;
        col_force[4] <= part_force + $signed({{2{sample_force[2]}}, sample_force});
        col_force_weight[4] <= part_force_weight + sample_force_weight;
        col_self[4] <= part_self;
        col_sea[4] <= part_sea + {2'd0, sample_sea};
        col_mountain[4] <= part_mountain + {2'd0, sample_mountain};
        col_natural[4] <= part_natural + {2'd0, sample_natural};
        col_house[4] <= part_house + {2'd0, sample_house};
        col_shop[4] <= part_shop + {2'd0, sample_shop};
        col_tall[4] <= part_tall + {2'd0, sample_tall};
      end
    end

    case (calc_state)
      ST_IDLE: if (start_event_calc) begin
        start_toggle_seen_calc <= start_toggle_sync2;
        source_bank_calc <= start_bank_sync2;
        cell_index <= 10'd0;
        guard_index <= 10'd0;
        guard_match <= 1'b1;
        cache_ready <= 1'b0;
        predicted_cell <= 1'b0;
        trajectory_valid_calc <= trajectory_sync2;
        model_active_calc <= model_sync2;
        calc_state <= validate_sync2 ? ST_GUARD :
            (model_sync2 ? ST_MODEL_WAIT : ST_INIT);
      end
      ST_GUARD: begin
        // Compare ALL 960 initial bytes, not a hash. ROM and grid q both lag
        // their address by one edge. The final byte is checked in GUARD_LAST.
        if (guard_index != 10'd0)
          guard_match <= guard_match && (calc_grid_dout == {1'b0, model_word[6:0]});
        if (guard_index == 10'd959) calc_state <= ST_GUARD_LAST;
        else guard_index <= guard_index + 10'd1;
      end
      ST_GUARD_LAST: begin
        trajectory_valid_calc <= guard_match && (calc_grid_dout == {1'b0, model_word[6:0]});
        calc_state <= ST_INIT;
      end
      ST_MODEL_WAIT: calc_state <= ST_MODEL;
      ST_MODEL: begin
        predicted_cell <= model_word[8:7] != 2'd0;
        case (model_word[8:7])
          2'd1: begin next_value <= 8'd0; calc_state <= ST_WRITE; end
          2'd2: begin next_value <= 8'd1; calc_state <= ST_WRITE; end
          2'd3: begin next_value <= 8'd100; calc_state <= ST_WRITE; end
          default: calc_state <= cache_ready ? ST_SUM : ST_INIT;
        endcase
      end
      ST_INIT: begin
        row_top <= top_row(cell_index[9:5]);
        issue_y <= top_row(cell_index[9:5]);
        issue_row <= 3'd0;
        issue_x <= cell_index[4:0] - 5'd2;
        reads_left <= 5'd25;
        calc_state <= ST_FILL;
      end
      ST_FILL: begin
        reads_left <= reads_left - 5'd1;
        if (reads_left == 5'd1) calc_state <= ST_DRAIN;
      end
      ST_DRAIN: begin
        // Consume the 25th sample here; all five columns are ready at ST_SUM.
        calc_state <= ST_SUM;
      end
      ST_SUM: begin
        weighted_sum_acc <= {3'd0, col_weight[0]} + {3'd0, col_weight[1]} + {3'd0, col_weight[2]}
            + {3'd0, col_weight[3]} + {3'd0, col_weight[4]} + {4'd0, col_sum[1]} + ( {4'd0, col_sum[2]} << 1) + {4'd0, col_sum[3]};
        raw_force_acc <= $signed({{2{col_force_weight[0][6]}}, col_force_weight[0]}) + $signed({{2{col_force_weight[1][6]}}, col_force_weight[1]}) + $signed({{2{col_force_weight[2][6]}}, col_force_weight[2]})
            + $signed({{2{col_force_weight[3][6]}}, col_force_weight[3]}) + $signed({{2{col_force_weight[4][6]}}, col_force_weight[4]}) + $signed({{4{col_force[1][4]}}, col_force[1]})
            + ($signed({{4{col_force[2][4]}}, col_force[2]}) <<< 1) + $signed({{4{col_force[3][4]}}, col_force[3]});
        self_value <= col_self[2];
        sea_count <= {2'd0, col_sea[0]} + {2'd0, col_sea[1]} + {2'd0, col_sea[2]} + {2'd0, col_sea[3]} + {2'd0, col_sea[4]};
        mountain_count <= {2'd0, col_mountain[0]} + {2'd0, col_mountain[1]} + {2'd0, col_mountain[2]} + {2'd0, col_mountain[3]} + {2'd0, col_mountain[4]};
        natural_count <= {2'd0, col_natural[0]} + {2'd0, col_natural[1]} + {2'd0, col_natural[2]} + {2'd0, col_natural[3]} + {2'd0, col_natural[4]};
        house_count <= {2'd0, col_house[0]} + {2'd0, col_house[1]} + {2'd0, col_house[2]} + {2'd0, col_house[3]} + {2'd0, col_house[4]};
        shop_count <= {2'd0, col_shop[0]} + {2'd0, col_shop[1]} + {2'd0, col_shop[2]} + {2'd0, col_shop[3]} + {2'd0, col_shop[4]};
        tall_count <= {2'd0, col_tall[0]} + {2'd0, col_tall[1]} + {2'd0, col_tall[2]} + {2'd0, col_tall[3]} + {2'd0, col_tall[4]};
        calc_state <= ST_AVG;
      end
      ST_AVG: begin
        avg_value <= divide65(weighted_sum_acc);
        urban_count <= house_count + shop_count + tall_count;
        calc_state <= ST_BIAS;
      end
      ST_BIAS: begin
        bias_value <= calc_bias(self_value, raw_force_acc, avg_value,
            sea_count, mountain_count, natural_count, urban_count, house_count, shop_count, tall_count);
        calc_state <= ST_DELTA;
      end
      ST_DELTA: begin
        delta_value <= calc_delta(self_value, raw_force_acc, avg_value, bias_value);
        calc_state <= ST_NEW_VALUE;
      end
      ST_NEW_VALUE: begin
        next_value <= calc_new_value(self_value, delta_value);
        calc_state <= ST_WRITE;
      end
      ST_WRITE: begin
        // The write commits now. The last prefetch sample also enters the cache
        // on this edge, ready for the following cell's ST_SUM.
        if (cell_index[4:0] == 5'd30) begin
          // x=31 will calculate from the old cache while fetching column x=30
          // of the next row. Reset only the read coordinates, not the cache.
          issue_x <= 5'd30;
          issue_y <= (row_top == 5'd29) ? 5'd0 : row_top + 5'd1;
          row_top <= (row_top == 5'd29) ? 5'd0 : row_top + 5'd1;
        end
        if (cell_index == 10'd959) calc_state <= ST_FINISH;
        else begin
          cell_index <= cell_index + 10'd1;
          if (model_active_calc) begin
            // A predicted cell did not prefetch the next column. Refill all
            // five columns before the next exact run, including row starts.
            cache_ready <= !predicted_cell && cell_index[4:0] != 5'd31;
            calc_state <= ST_MODEL;
          end else if (cell_index[4:0] == 5'd31) begin
            // Column x=30 is now cached; fill only x=31,0,1,2 for the new row.
            reads_left <= 5'd20;
            calc_state <= ST_FILL;
          end else calc_state <= ST_SUM;
        end
      end
      ST_FINISH: begin
        // The final RAM write committed on the previous edge, before DONE.
        done_toggle_calc <= ~done_toggle_calc;
        calc_state <= ST_IDLE;
      end
      default: calc_state <= ST_IDLE;
    endcase
  end
end

endmodule

// -------------------------------------------------------------------------------------------------
// 2 KiB dual-clock true-dual-port RAM.
// Port A and port B use independent clocks.  Cross-port same-address read/write behavior is not
// relied upon: CPU grid access is blocked while the calculator is active.
// -------------------------------------------------------------------------------------------------
module city_grid_dpram_dc
#(
  parameter ADDR_WIDTH = 11,
  parameter DATA_WIDTH = 8
)
(
  input  wire                  clk_a,
  input  wire                  we_a,
  input  wire [ADDR_WIDTH-1:0] addr_a,
  input  wire [DATA_WIDTH-1:0] data_a,
  output reg  [DATA_WIDTH-1:0] q_a,

  input  wire                  clk_b,
  input  wire                  we_b,
  input  wire [ADDR_WIDTH-1:0] addr_b,
  input  wire [DATA_WIDTH-1:0] data_b,
  output reg  [DATA_WIDTH-1:0] q_b
);

(* ramstyle = "M9K" *) reg [DATA_WIDTH-1:0] ram [0:(1<<ADDR_WIDTH)-1];

always @(posedge clk_a) begin
  if (we_a)
    ram[addr_a] <= data_a;
  q_a <= ram[addr_a];
end

always @(posedge clk_b) begin
  if (we_b)
    ram[addr_b] <= data_b;
  q_b <= ram[addr_b];
end

endmodule

// BEGIN LEARNED ROM (generated by eval/learned.py)
module city_learned_rom (
  input wire clk,
  input wire [9:0] address,
  output reg [8:0] q
);
(* ramstyle = "M9K" *) reg [8:0] rom [0:1023];
initial begin
  // seed 6502, generations 0..1280; SHA256 92e2aac015c470f8362978a4f68c127a1867bd61ea9e2f338446c7271bffcb05
  rom[0] = 9'h10d;
  rom[1] = 9'h10d;
  rom[2] = 9'h114;
  rom[3] = 9'h111;
  rom[4] = 9'h112;
  rom[5] = 9'h115;
  rom[6] = 9'h080;
  rom[7] = 9'h11f;
  rom[8] = 9'h114;
  rom[9] = 9'h108;
  rom[10] = 9'h120;
  rom[11] = 9'h10d;
  rom[12] = 9'h11e;
  rom[13] = 9'h116;
  rom[14] = 9'h11d;
  rom[15] = 9'h10b;
  rom[16] = 9'h116;
  rom[17] = 9'h114;
  rom[18] = 9'h11c;
  rom[19] = 9'h113;
  rom[20] = 9'h114;
  rom[21] = 9'h108;
  rom[22] = 9'h11c;
  rom[23] = 9'h111;
  rom[24] = 9'h112;
  rom[25] = 9'h11f;
  rom[26] = 9'h111;
  rom[27] = 9'h114;
  rom[28] = 9'h114;
  rom[29] = 9'h111;
  rom[30] = 9'h116;
  rom[31] = 9'h111;
  rom[32] = 9'h112;
  rom[33] = 9'h11e;
  rom[34] = 9'h113;
  rom[35] = 9'h11b;
  rom[36] = 9'h112;
  rom[37] = 9'h080;
  rom[38] = 9'h080;
  rom[39] = 9'h114;
  rom[40] = 9'h10c;
  rom[41] = 9'h113;
  rom[42] = 9'h113;
  rom[43] = 9'h11c;
  rom[44] = 9'h115;
  rom[45] = 9'h108;
  rom[46] = 9'h112;
  rom[47] = 9'h111;
  rom[48] = 9'h115;
  rom[49] = 9'h11c;
  rom[50] = 9'h10c;
  rom[51] = 9'h10a;
  rom[52] = 9'h111;
  rom[53] = 9'h114;
  rom[54] = 9'h112;
  rom[55] = 9'h10d;
  rom[56] = 9'h111;
  rom[57] = 9'h116;
  rom[58] = 9'h10a;
  rom[59] = 9'h115;
  rom[60] = 9'h113;
  rom[61] = 9'h113;
  rom[62] = 9'h116;
  rom[63] = 9'h113;
  rom[64] = 9'h11f;
  rom[65] = 9'h111;
  rom[66] = 9'h113;
  rom[67] = 9'h116;
  rom[68] = 9'h10a;
  rom[69] = 9'h080;
  rom[70] = 9'h080;
  rom[71] = 9'h114;
  rom[72] = 9'h111;
  rom[73] = 9'h116;
  rom[74] = 9'h113;
  rom[75] = 9'h115;
  rom[76] = 9'h113;
  rom[77] = 9'h111;
  rom[78] = 9'h11c;
  rom[79] = 9'h11b;
  rom[80] = 9'h111;
  rom[81] = 9'h111;
  rom[82] = 9'h111;
  rom[83] = 9'h10d;
  rom[84] = 9'h111;
  rom[85] = 9'h116;
  rom[86] = 9'h113;
  rom[87] = 9'h114;
  rom[88] = 9'h11d;
  rom[89] = 9'h11e;
  rom[90] = 9'h116;
  rom[91] = 9'h119;
  rom[92] = 9'h115;
  rom[93] = 9'h120;
  rom[94] = 9'h11b;
  rom[95] = 9'h10b;
  rom[96] = 9'h10c;
  rom[97] = 9'h10c;
  rom[98] = 9'h112;
  rom[99] = 9'h11a;
  rom[100] = 9'h10a;
  rom[101] = 9'h111;
  rom[102] = 9'h080;
  rom[103] = 9'h108;
  rom[104] = 9'h112;
  rom[105] = 9'h11c;
  rom[106] = 9'h11e;
  rom[107] = 9'h108;
  rom[108] = 9'h114;
  rom[109] = 9'h109;
  rom[110] = 9'h111;
  rom[111] = 9'h10d;
  rom[112] = 9'h116;
  rom[113] = 9'h115;
  rom[114] = 9'h116;
  rom[115] = 9'h116;
  rom[116] = 9'h114;
  rom[117] = 9'h115;
  rom[118] = 9'h108;
  rom[119] = 9'h115;
  rom[120] = 9'h109;
  rom[121] = 9'h113;
  rom[122] = 9'h109;
  rom[123] = 9'h10d;
  rom[124] = 9'h114;
  rom[125] = 9'h11c;
  rom[126] = 9'h113;
  rom[127] = 9'h116;
  rom[128] = 9'h11e;
  rom[129] = 9'h116;
  rom[130] = 9'h112;
  rom[131] = 9'h115;
  rom[132] = 9'h114;
  rom[133] = 9'h11f;
  rom[134] = 9'h108;
  rom[135] = 9'h080;
  rom[136] = 9'h080;
  rom[137] = 9'h11f;
  rom[138] = 9'h11e;
  rom[139] = 9'h112;
  rom[140] = 9'h112;
  rom[141] = 9'h112;
  rom[142] = 9'h10c;
  rom[143] = 9'h112;
  rom[144] = 9'h109;
  rom[145] = 9'h10d;
  rom[146] = 9'h114;
  rom[147] = 9'h111;
  rom[148] = 9'h114;
  rom[149] = 9'h111;
  rom[150] = 9'h116;
  rom[151] = 9'h113;
  rom[152] = 9'h116;
  rom[153] = 9'h11d;
  rom[154] = 9'h111;
  rom[155] = 9'h116;
  rom[156] = 9'h120;
  rom[157] = 9'h101;
  rom[158] = 9'h114;
  rom[159] = 9'h115;
  rom[160] = 9'h10b;
  rom[161] = 9'h116;
  rom[162] = 9'h111;
  rom[163] = 9'h119;
  rom[164] = 9'h112;
  rom[165] = 9'h11a;
  rom[166] = 9'h114;
  rom[167] = 9'h112;
  rom[168] = 9'h080;
  rom[169] = 9'h080;
  rom[170] = 9'h015;
  rom[171] = 9'h016;
  rom[172] = 9'h008;
  rom[173] = 9'h015;
  rom[174] = 9'h116;
  rom[175] = 9'h11d;
  rom[176] = 9'h111;
  rom[177] = 9'h10b;
  rom[178] = 9'h113;
  rom[179] = 9'h11b;
  rom[180] = 9'h111;
  rom[181] = 9'h10b;
  rom[182] = 9'h114;
  rom[183] = 9'h112;
  rom[184] = 9'h111;
  rom[185] = 9'h114;
  rom[186] = 9'h10a;
  rom[187] = 9'h111;
  rom[188] = 9'h101;
  rom[189] = 9'h115;
  rom[190] = 9'h101;
  rom[191] = 9'h11f;
  rom[192] = 9'h111;
  rom[193] = 9'h111;
  rom[194] = 9'h119;
  rom[195] = 9'h114;
  rom[196] = 9'h10a;
  rom[197] = 9'h112;
  rom[198] = 9'h11a;
  rom[199] = 9'h116;
  rom[200] = 9'h080;
  rom[201] = 9'h196;
  rom[202] = 9'h195;
  rom[203] = 9'h015;
  rom[204] = 9'h023;
  rom[205] = 9'h013;
  rom[206] = 9'h00d;
  rom[207] = 9'h111;
  rom[208] = 9'h113;
  rom[209] = 9'h113;
  rom[210] = 9'h10c;
  rom[211] = 9'h11e;
  rom[212] = 9'h111;
  rom[213] = 9'h11c;
  rom[214] = 9'h119;
  rom[215] = 9'h116;
  rom[216] = 9'h015;
  rom[217] = 9'h012;
  rom[218] = 9'h012;
  rom[219] = 9'h015;
  rom[220] = 9'h013;
  rom[221] = 9'h109;
  rom[222] = 9'h101;
  rom[223] = 9'h11a;
  rom[224] = 9'h11d;
  rom[225] = 9'h111;
  rom[226] = 9'h120;
  rom[227] = 9'h120;
  rom[228] = 9'h10a;
  rom[229] = 9'h111;
  rom[230] = 9'h111;
  rom[231] = 9'h080;
  rom[232] = 9'h080;
  rom[233] = 9'h196;
  rom[234] = 9'h012;
  rom[235] = 9'h024;
  rom[236] = 9'h026;
  rom[237] = 9'h024;
  rom[238] = 9'h011;
  rom[239] = 9'h016;
  rom[240] = 9'h120;
  rom[241] = 9'h119;
  rom[242] = 9'h114;
  rom[243] = 9'h114;
  rom[244] = 9'h114;
  rom[245] = 9'h115;
  rom[246] = 9'h113;
  rom[247] = 9'h011;
  rom[248] = 9'h016;
  rom[249] = 9'h011;
  rom[250] = 9'h01c;
  rom[251] = 9'h023;
  rom[252] = 9'h009;
  rom[253] = 9'h00b;
  rom[254] = 9'h011;
  rom[255] = 9'h116;
  rom[256] = 9'h114;
  rom[257] = 9'h112;
  rom[258] = 9'h114;
  rom[259] = 9'h113;
  rom[260] = 9'h114;
  rom[261] = 9'h115;
  rom[262] = 9'h113;
  rom[263] = 9'h111;
  rom[264] = 9'h080;
  rom[265] = 9'h080;
  rom[266] = 9'h024;
  rom[267] = 9'h026;
  rom[268] = 9'h02a;
  rom[269] = 9'h027;
  rom[270] = 9'h023;
  rom[271] = 9'h012;
  rom[272] = 9'h020;
  rom[273] = 9'h016;
  rom[274] = 9'h012;
  rom[275] = 9'h015;
  rom[276] = 9'h014;
  rom[277] = 9'h011;
  rom[278] = 9'h014;
  rom[279] = 9'h015;
  rom[280] = 9'h01a;
  rom[281] = 9'h013;
  rom[282] = 9'h023;
  rom[283] = 9'h025;
  rom[284] = 9'h023;
  rom[285] = 9'h011;
  rom[286] = 9'h014;
  rom[287] = 9'h115;
  rom[288] = 9'h114;
  rom[289] = 9'h112;
  rom[290] = 9'h10c;
  rom[291] = 9'h11f;
  rom[292] = 9'h112;
  rom[293] = 9'h114;
  rom[294] = 9'h112;
  rom[295] = 9'h080;
  rom[296] = 9'h113;
  rom[297] = 9'h195;
  rom[298] = 9'h195;
  rom[299] = 9'h023;
  rom[300] = 9'h026;
  rom[301] = 9'h023;
  rom[302] = 9'h016;
  rom[303] = 9'h015;
  rom[304] = 9'h011;
  rom[305] = 9'h014;
  rom[306] = 9'h01f;
  rom[307] = 9'h019;
  rom[308] = 9'h011;
  rom[309] = 9'h014;
  rom[310] = 9'h009;
  rom[311] = 9'h014;
  rom[312] = 9'h019;
  rom[313] = 9'h023;
  rom[314] = 9'h026;
  rom[315] = 9'h028;
  rom[316] = 9'h026;
  rom[317] = 9'h023;
  rom[318] = 9'h00b;
  rom[319] = 9'h011;
  rom[320] = 9'h111;
  rom[321] = 9'h11d;
  rom[322] = 9'h113;
  rom[323] = 9'h112;
  rom[324] = 9'h10a;
  rom[325] = 9'h112;
  rom[326] = 9'h114;
  rom[327] = 9'h11a;
  rom[328] = 9'h080;
  rom[329] = 9'h080;
  rom[330] = 9'h195;
  rom[331] = 9'h015;
  rom[332] = 9'h023;
  rom[333] = 9'h011;
  rom[334] = 9'h016;
  rom[335] = 9'h011;
  rom[336] = 9'h015;
  rom[337] = 9'h00c;
  rom[338] = 9'h013;
  rom[339] = 9'h01c;
  rom[340] = 9'h011;
  rom[341] = 9'h016;
  rom[342] = 9'h011;
  rom[343] = 9'h01c;
  rom[344] = 9'h023;
  rom[345] = 9'h025;
  rom[346] = 9'h029;
  rom[347] = 9'h03f;
  rom[348] = 9'h029;
  rom[349] = 9'h026;
  rom[350] = 9'h023;
  rom[351] = 9'h012;
  rom[352] = 9'h113;
  rom[353] = 9'h113;
  rom[354] = 9'h114;
  rom[355] = 9'h11e;
  rom[356] = 9'h10a;
  rom[357] = 9'h111;
  rom[358] = 9'h10a;
  rom[359] = 9'h115;
  rom[360] = 9'h080;
  rom[361] = 9'h080;
  rom[362] = 9'h012;
  rom[363] = 9'h00a;
  rom[364] = 9'h014;
  rom[365] = 9'h012;
  rom[366] = 9'h011;
  rom[367] = 9'h014;
  rom[368] = 9'h012;
  rom[369] = 9'h00a;
  rom[370] = 9'h012;
  rom[371] = 9'h016;
  rom[372] = 9'h014;
  rom[373] = 9'h01d;
  rom[374] = 9'h015;
  rom[375] = 9'h013;
  rom[376] = 9'h014;
  rom[377] = 9'h023;
  rom[378] = 9'h026;
  rom[379] = 9'h029;
  rom[380] = 9'h025;
  rom[381] = 9'h023;
  rom[382] = 9'h011;
  rom[383] = 9'h01c;
  rom[384] = 9'h116;
  rom[385] = 9'h10b;
  rom[386] = 9'h112;
  rom[387] = 9'h111;
  rom[388] = 9'h114;
  rom[389] = 9'h10c;
  rom[390] = 9'h115;
  rom[391] = 9'h113;
  rom[392] = 9'h080;
  rom[393] = 9'h013;
  rom[394] = 9'h014;
  rom[395] = 9'h012;
  rom[396] = 9'h012;
  rom[397] = 9'h012;
  rom[398] = 9'h015;
  rom[399] = 9'h00d;
  rom[400] = 9'h027;
  rom[401] = 9'h012;
  rom[402] = 9'h016;
  rom[403] = 9'h013;
  rom[404] = 9'h016;
  rom[405] = 9'h011;
  rom[406] = 9'h01e;
  rom[407] = 9'h01b;
  rom[408] = 9'h00b;
  rom[409] = 9'h013;
  rom[410] = 9'h023;
  rom[411] = 9'h026;
  rom[412] = 9'h023;
  rom[413] = 9'h015;
  rom[414] = 9'h014;
  rom[415] = 9'h01f;
  rom[416] = 9'h116;
  rom[417] = 9'h120;
  rom[418] = 9'h113;
  rom[419] = 9'h11d;
  rom[420] = 9'h112;
  rom[421] = 9'h114;
  rom[422] = 9'h11e;
  rom[423] = 9'h10d;
  rom[424] = 9'h080;
  rom[425] = 9'h080;
  rom[426] = 9'h008;
  rom[427] = 9'h016;
  rom[428] = 9'h00a;
  rom[429] = 9'h013;
  rom[430] = 9'h016;
  rom[431] = 9'h027;
  rom[432] = 9'h02b;
  rom[433] = 9'h027;
  rom[434] = 9'h015;
  rom[435] = 9'h01f;
  rom[436] = 9'h011;
  rom[437] = 9'h014;
  rom[438] = 9'h014;
  rom[439] = 9'h016;
  rom[440] = 9'h013;
  rom[441] = 9'h012;
  rom[442] = 9'h019;
  rom[443] = 9'h023;
  rom[444] = 9'h01b;
  rom[445] = 9'h015;
  rom[446] = 9'h014;
  rom[447] = 9'h111;
  rom[448] = 9'h113;
  rom[449] = 9'h115;
  rom[450] = 9'h111;
  rom[451] = 9'h114;
  rom[452] = 9'h10a;
  rom[453] = 9'h11a;
  rom[454] = 9'h10d;
  rom[455] = 9'h080;
  rom[456] = 9'h080;
  rom[457] = 9'h109;
  rom[458] = 9'h108;
  rom[459] = 9'h011;
  rom[460] = 9'h011;
  rom[461] = 9'h013;
  rom[462] = 9'h027;
  rom[463] = 9'h02a;
  rom[464] = 9'h02e;
  rom[465] = 9'h02a;
  rom[466] = 9'h028;
  rom[467] = 9'h01a;
  rom[468] = 9'h013;
  rom[469] = 9'h00d;
  rom[470] = 9'h00c;
  rom[471] = 9'h00b;
  rom[472] = 9'h013;
  rom[473] = 9'h014;
  rom[474] = 9'h00b;
  rom[475] = 9'h011;
  rom[476] = 9'h013;
  rom[477] = 9'h012;
  rom[478] = 9'h111;
  rom[479] = 9'h116;
  rom[480] = 9'h115;
  rom[481] = 9'h10a;
  rom[482] = 9'h112;
  rom[483] = 9'h11c;
  rom[484] = 9'h10a;
  rom[485] = 9'h11d;
  rom[486] = 9'h080;
  rom[487] = 9'h111;
  rom[488] = 9'h11a;
  rom[489] = 9'h114;
  rom[490] = 9'h114;
  rom[491] = 9'h013;
  rom[492] = 9'h01e;
  rom[493] = 9'h028;
  rom[494] = 9'h02a;
  rom[495] = 9'h02d;
  rom[496] = 9'h030;
  rom[497] = 9'h040;
  rom[498] = 9'h02a;
  rom[499] = 9'h027;
  rom[500] = 9'h014;
  rom[501] = 9'h02b;
  rom[502] = 9'h00a;
  rom[503] = 9'h01d;
  rom[504] = 9'h01e;
  rom[505] = 9'h00a;
  rom[506] = 9'h016;
  rom[507] = 9'h012;
  rom[508] = 9'h009;
  rom[509] = 9'h114;
  rom[510] = 9'h11d;
  rom[511] = 9'h114;
  rom[512] = 9'h109;
  rom[513] = 9'h114;
  rom[514] = 9'h11c;
  rom[515] = 9'h113;
  rom[516] = 9'h114;
  rom[517] = 9'h115;
  rom[518] = 9'h11d;
  rom[519] = 9'h080;
  rom[520] = 9'h080;
  rom[521] = 9'h111;
  rom[522] = 9'h114;
  rom[523] = 9'h120;
  rom[524] = 9'h00d;
  rom[525] = 9'h014;
  rom[526] = 9'h028;
  rom[527] = 9'h02b;
  rom[528] = 9'h02d;
  rom[529] = 9'h02a;
  rom[530] = 9'h028;
  rom[531] = 9'h011;
  rom[532] = 9'h02c;
  rom[533] = 9'h02e;
  rom[534] = 9'h02c;
  rom[535] = 9'h013;
  rom[536] = 9'h012;
  rom[537] = 9'h011;
  rom[538] = 9'h01f;
  rom[539] = 9'h009;
  rom[540] = 9'h114;
  rom[541] = 9'h111;
  rom[542] = 9'h11c;
  rom[543] = 9'h113;
  rom[544] = 9'h112;
  rom[545] = 9'h114;
  rom[546] = 9'h11b;
  rom[547] = 9'h115;
  rom[548] = 9'h112;
  rom[549] = 9'h114;
  rom[550] = 9'h116;
  rom[551] = 9'h080;
  rom[552] = 9'h080;
  rom[553] = 9'h11d;
  rom[554] = 9'h108;
  rom[555] = 9'h116;
  rom[556] = 9'h015;
  rom[557] = 9'h011;
  rom[558] = 9'h016;
  rom[559] = 9'h028;
  rom[560] = 9'h02a;
  rom[561] = 9'h028;
  rom[562] = 9'h013;
  rom[563] = 9'h02c;
  rom[564] = 9'h02e;
  rom[565] = 9'h031;
  rom[566] = 9'h02f;
  rom[567] = 9'h02c;
  rom[568] = 9'h013;
  rom[569] = 9'h00d;
  rom[570] = 9'h011;
  rom[571] = 9'h00a;
  rom[572] = 9'h113;
  rom[573] = 9'h113;
  rom[574] = 9'h114;
  rom[575] = 9'h108;
  rom[576] = 9'h10c;
  rom[577] = 9'h115;
  rom[578] = 9'h115;
  rom[579] = 9'h112;
  rom[580] = 9'h10a;
  rom[581] = 9'h112;
  rom[582] = 9'h112;
  rom[583] = 9'h116;
  rom[584] = 9'h080;
  rom[585] = 9'h120;
  rom[586] = 9'h108;
  rom[587] = 9'h108;
  rom[588] = 9'h013;
  rom[589] = 9'h011;
  rom[590] = 9'h014;
  rom[591] = 9'h015;
  rom[592] = 9'h027;
  rom[593] = 9'h011;
  rom[594] = 9'h02b;
  rom[595] = 9'h02e;
  rom[596] = 9'h032;
  rom[597] = 9'h034;
  rom[598] = 9'h042;
  rom[599] = 9'h02f;
  rom[600] = 9'h02c;
  rom[601] = 9'h192;
  rom[602] = 9'h11e;
  rom[603] = 9'h111;
  rom[604] = 9'h111;
  rom[605] = 9'h116;
  rom[606] = 9'h115;
  rom[607] = 9'h11c;
  rom[608] = 9'h111;
  rom[609] = 9'h115;
  rom[610] = 9'h11a;
  rom[611] = 9'h114;
  rom[612] = 9'h10a;
  rom[613] = 9'h111;
  rom[614] = 9'h111;
  rom[615] = 9'h080;
  rom[616] = 9'h080;
  rom[617] = 9'h112;
  rom[618] = 9'h114;
  rom[619] = 9'h01b;
  rom[620] = 9'h014;
  rom[621] = 9'h012;
  rom[622] = 9'h01b;
  rom[623] = 9'h01e;
  rom[624] = 9'h016;
  rom[625] = 9'h01b;
  rom[626] = 9'h014;
  rom[627] = 9'h02c;
  rom[628] = 9'h02f;
  rom[629] = 9'h031;
  rom[630] = 9'h02e;
  rom[631] = 9'h02b;
  rom[632] = 9'h009;
  rom[633] = 9'h019;
  rom[634] = 9'h116;
  rom[635] = 9'h11c;
  rom[636] = 9'h114;
  rom[637] = 9'h116;
  rom[638] = 9'h11b;
  rom[639] = 9'h112;
  rom[640] = 9'h11e;
  rom[641] = 9'h116;
  rom[642] = 9'h114;
  rom[643] = 9'h111;
  rom[644] = 9'h114;
  rom[645] = 9'h113;
  rom[646] = 9'h115;
  rom[647] = 9'h080;
  rom[648] = 9'h080;
  rom[649] = 9'h015;
  rom[650] = 9'h016;
  rom[651] = 9'h014;
  rom[652] = 9'h012;
  rom[653] = 9'h012;
  rom[654] = 9'h013;
  rom[655] = 9'h014;
  rom[656] = 9'h012;
  rom[657] = 9'h014;
  rom[658] = 9'h01a;
  rom[659] = 9'h013;
  rom[660] = 9'h02b;
  rom[661] = 9'h02e;
  rom[662] = 9'h02b;
  rom[663] = 9'h015;
  rom[664] = 9'h016;
  rom[665] = 9'h115;
  rom[666] = 9'h11d;
  rom[667] = 9'h112;
  rom[668] = 9'h109;
  rom[669] = 9'h11f;
  rom[670] = 9'h11a;
  rom[671] = 9'h113;
  rom[672] = 9'h10b;
  rom[673] = 9'h116;
  rom[674] = 9'h115;
  rom[675] = 9'h113;
  rom[676] = 9'h114;
  rom[677] = 9'h114;
  rom[678] = 9'h080;
  rom[679] = 9'h1a7;
  rom[680] = 9'h1a5;
  rom[681] = 9'h191;
  rom[682] = 9'h19d;
  rom[683] = 9'h012;
  rom[684] = 9'h013;
  rom[685] = 9'h013;
  rom[686] = 9'h01a;
  rom[687] = 9'h013;
  rom[688] = 9'h011;
  rom[689] = 9'h012;
  rom[690] = 9'h008;
  rom[691] = 9'h01b;
  rom[692] = 9'h013;
  rom[693] = 9'h02b;
  rom[694] = 9'h009;
  rom[695] = 9'h016;
  rom[696] = 9'h011;
  rom[697] = 9'h120;
  rom[698] = 9'h111;
  rom[699] = 9'h113;
  rom[700] = 9'h11f;
  rom[701] = 9'h11b;
  rom[702] = 9'h114;
  rom[703] = 9'h115;
  rom[704] = 9'h111;
  rom[705] = 9'h11f;
  rom[706] = 9'h113;
  rom[707] = 9'h116;
  rom[708] = 9'h10c;
  rom[709] = 9'h125;
  rom[710] = 9'h080;
  rom[711] = 9'h080;
  rom[712] = 9'h1a7;
  rom[713] = 9'h025;
  rom[714] = 9'h01d;
  rom[715] = 9'h011;
  rom[716] = 9'h011;
  rom[717] = 9'h013;
  rom[718] = 9'h014;
  rom[719] = 9'h015;
  rom[720] = 9'h013;
  rom[721] = 9'h00a;
  rom[722] = 9'h013;
  rom[723] = 9'h01e;
  rom[724] = 9'h013;
  rom[725] = 9'h016;
  rom[726] = 9'h013;
  rom[727] = 9'h114;
  rom[728] = 9'h111;
  rom[729] = 9'h109;
  rom[730] = 9'h11c;
  rom[731] = 9'h111;
  rom[732] = 9'h113;
  rom[733] = 9'h112;
  rom[734] = 9'h115;
  rom[735] = 9'h114;
  rom[736] = 9'h11d;
  rom[737] = 9'h111;
  rom[738] = 9'h114;
  rom[739] = 9'h112;
  rom[740] = 9'h125;
  rom[741] = 9'h080;
  rom[742] = 9'h080;
  rom[743] = 9'h1ae;
  rom[744] = 9'h02a;
  rom[745] = 9'h028;
  rom[746] = 9'h025;
  rom[747] = 9'h015;
  rom[748] = 9'h11a;
  rom[749] = 9'h114;
  rom[750] = 9'h10c;
  rom[751] = 9'h112;
  rom[752] = 9'h109;
  rom[753] = 9'h108;
  rom[754] = 9'h112;
  rom[755] = 9'h116;
  rom[756] = 9'h116;
  rom[757] = 9'h113;
  rom[758] = 9'h111;
  rom[759] = 9'h113;
  rom[760] = 9'h116;
  rom[761] = 9'h11f;
  rom[762] = 9'h112;
  rom[763] = 9'h114;
  rom[764] = 9'h112;
  rom[765] = 9'h114;
  rom[766] = 9'h10c;
  rom[767] = 9'h109;
  rom[768] = 9'h114;
  rom[769] = 9'h109;
  rom[770] = 9'h112;
  rom[771] = 9'h115;
  rom[772] = 9'h114;
  rom[773] = 9'h125;
  rom[774] = 9'h080;
  rom[775] = 9'h1aa;
  rom[776] = 9'h027;
  rom[777] = 9'h025;
  rom[778] = 9'h016;
  rom[779] = 9'h01c;
  rom[780] = 9'h10d;
  rom[781] = 9'h120;
  rom[782] = 9'h119;
  rom[783] = 9'h114;
  rom[784] = 9'h120;
  rom[785] = 9'h116;
  rom[786] = 9'h116;
  rom[787] = 9'h111;
  rom[788] = 9'h116;
  rom[789] = 9'h115;
  rom[790] = 9'h112;
  rom[791] = 9'h111;
  rom[792] = 9'h11a;
  rom[793] = 9'h10a;
  rom[794] = 9'h115;
  rom[795] = 9'h11e;
  rom[796] = 9'h116;
  rom[797] = 9'h11d;
  rom[798] = 9'h109;
  rom[799] = 9'h108;
  rom[800] = 9'h11c;
  rom[801] = 9'h11a;
  rom[802] = 9'h113;
  rom[803] = 9'h111;
  rom[804] = 9'h114;
  rom[805] = 9'h120;
  rom[806] = 9'h080;
  rom[807] = 9'h080;
  rom[808] = 9'h1a5;
  rom[809] = 9'h195;
  rom[810] = 9'h01b;
  rom[811] = 9'h012;
  rom[812] = 9'h115;
  rom[813] = 9'h111;
  rom[814] = 9'h10b;
  rom[815] = 9'h111;
  rom[816] = 9'h113;
  rom[817] = 9'h120;
  rom[818] = 9'h115;
  rom[819] = 9'h111;
  rom[820] = 9'h113;
  rom[821] = 9'h11e;
  rom[822] = 9'h116;
  rom[823] = 9'h112;
  rom[824] = 9'h108;
  rom[825] = 9'h112;
  rom[826] = 9'h113;
  rom[827] = 9'h10a;
  rom[828] = 9'h113;
  rom[829] = 9'h119;
  rom[830] = 9'h112;
  rom[831] = 9'h115;
  rom[832] = 9'h113;
  rom[833] = 9'h113;
  rom[834] = 9'h11f;
  rom[835] = 9'h101;
  rom[836] = 9'h115;
  rom[837] = 9'h080;
  rom[838] = 9'h080;
  rom[839] = 9'h024;
  rom[840] = 9'h00c;
  rom[841] = 9'h012;
  rom[842] = 9'h01b;
  rom[843] = 9'h008;
  rom[844] = 9'h119;
  rom[845] = 9'h11f;
  rom[846] = 9'h120;
  rom[847] = 9'h10a;
  rom[848] = 9'h115;
  rom[849] = 9'h113;
  rom[850] = 9'h108;
  rom[851] = 9'h114;
  rom[852] = 9'h113;
  rom[853] = 9'h11a;
  rom[854] = 9'h10c;
  rom[855] = 9'h116;
  rom[856] = 9'h115;
  rom[857] = 9'h11a;
  rom[858] = 9'h116;
  rom[859] = 9'h113;
  rom[860] = 9'h11d;
  rom[861] = 9'h116;
  rom[862] = 9'h115;
  rom[863] = 9'h114;
  rom[864] = 9'h113;
  rom[865] = 9'h108;
  rom[866] = 9'h112;
  rom[867] = 9'h116;
  rom[868] = 9'h101;
  rom[869] = 9'h080;
  rom[870] = 9'h111;
  rom[871] = 9'h111;
  rom[872] = 9'h11c;
  rom[873] = 9'h120;
  rom[874] = 9'h116;
  rom[875] = 9'h11f;
  rom[876] = 9'h114;
  rom[877] = 9'h112;
  rom[878] = 9'h113;
  rom[879] = 9'h112;
  rom[880] = 9'h114;
  rom[881] = 9'h111;
  rom[882] = 9'h116;
  rom[883] = 9'h114;
  rom[884] = 9'h116;
  rom[885] = 9'h113;
  rom[886] = 9'h10a;
  rom[887] = 9'h115;
  rom[888] = 9'h116;
  rom[889] = 9'h115;
  rom[890] = 9'h112;
  rom[891] = 9'h114;
  rom[892] = 9'h116;
  rom[893] = 9'h116;
  rom[894] = 9'h115;
  rom[895] = 9'h11c;
  rom[896] = 9'h116;
  rom[897] = 9'h114;
  rom[898] = 9'h10d;
  rom[899] = 9'h113;
  rom[900] = 9'h080;
  rom[901] = 9'h080;
  rom[902] = 9'h11f;
  rom[903] = 9'h111;
  rom[904] = 9'h10d;
  rom[905] = 9'h11b;
  rom[906] = 9'h112;
  rom[907] = 9'h116;
  rom[908] = 9'h112;
  rom[909] = 9'h11e;
  rom[910] = 9'h11f;
  rom[911] = 9'h11e;
  rom[912] = 9'h116;
  rom[913] = 9'h109;
  rom[914] = 9'h114;
  rom[915] = 9'h115;
  rom[916] = 9'h116;
  rom[917] = 9'h10c;
  rom[918] = 9'h114;
  rom[919] = 9'h113;
  rom[920] = 9'h114;
  rom[921] = 9'h119;
  rom[922] = 9'h111;
  rom[923] = 9'h112;
  rom[924] = 9'h109;
  rom[925] = 9'h11b;
  rom[926] = 9'h112;
  rom[927] = 9'h111;
  rom[928] = 9'h112;
  rom[929] = 9'h112;
  rom[930] = 9'h11d;
  rom[931] = 9'h115;
  rom[932] = 9'h114;
  rom[933] = 9'h080;
  rom[934] = 9'h080;
  rom[935] = 9'h11c;
  rom[936] = 9'h11b;
  rom[937] = 9'h113;
  rom[938] = 9'h113;
  rom[939] = 9'h109;
  rom[940] = 9'h113;
  rom[941] = 9'h113;
  rom[942] = 9'h114;
  rom[943] = 9'h111;
  rom[944] = 9'h115;
  rom[945] = 9'h116;
  rom[946] = 9'h11d;
  rom[947] = 9'h115;
  rom[948] = 9'h113;
  rom[949] = 9'h114;
  rom[950] = 9'h112;
  rom[951] = 9'h114;
  rom[952] = 9'h115;
  rom[953] = 9'h116;
  rom[954] = 9'h113;
  rom[955] = 9'h113;
  rom[956] = 9'h11b;
  rom[957] = 9'h10c;
  rom[958] = 9'h11e;
  rom[959] = 9'h113;
  rom[960] = 9'h000;
  rom[961] = 9'h000;
  rom[962] = 9'h000;
  rom[963] = 9'h000;
  rom[964] = 9'h000;
  rom[965] = 9'h000;
  rom[966] = 9'h000;
  rom[967] = 9'h000;
  rom[968] = 9'h000;
  rom[969] = 9'h000;
  rom[970] = 9'h000;
  rom[971] = 9'h000;
  rom[972] = 9'h000;
  rom[973] = 9'h000;
  rom[974] = 9'h000;
  rom[975] = 9'h000;
  rom[976] = 9'h000;
  rom[977] = 9'h000;
  rom[978] = 9'h000;
  rom[979] = 9'h000;
  rom[980] = 9'h000;
  rom[981] = 9'h000;
  rom[982] = 9'h000;
  rom[983] = 9'h000;
  rom[984] = 9'h000;
  rom[985] = 9'h000;
  rom[986] = 9'h000;
  rom[987] = 9'h000;
  rom[988] = 9'h000;
  rom[989] = 9'h000;
  rom[990] = 9'h000;
  rom[991] = 9'h000;
  rom[992] = 9'h000;
  rom[993] = 9'h000;
  rom[994] = 9'h000;
  rom[995] = 9'h000;
  rom[996] = 9'h000;
  rom[997] = 9'h000;
  rom[998] = 9'h000;
  rom[999] = 9'h000;
  rom[1000] = 9'h000;
  rom[1001] = 9'h000;
  rom[1002] = 9'h000;
  rom[1003] = 9'h000;
  rom[1004] = 9'h000;
  rom[1005] = 9'h000;
  rom[1006] = 9'h000;
  rom[1007] = 9'h000;
  rom[1008] = 9'h000;
  rom[1009] = 9'h000;
  rom[1010] = 9'h000;
  rom[1011] = 9'h000;
  rom[1012] = 9'h000;
  rom[1013] = 9'h000;
  rom[1014] = 9'h000;
  rom[1015] = 9'h000;
  rom[1016] = 9'h000;
  rom[1017] = 9'h000;
  rom[1018] = 9'h000;
  rom[1019] = 9'h000;
  rom[1020] = 9'h000;
  rom[1021] = 9'h000;
  rom[1022] = 9'h000;
  rom[1023] = 9'h000;
end
always @(posedge clk) q <= rom[address];
endmodule
// END LEARNED ROM
